### ISSUE TITLE
Increase section numbering depth to level 5

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/er_template#34]
Please add this to `er.adoc` to enable section numbering down to level 5:

```
:sectnums:
:sectnumlevels: 5
```

**Comment by ogcscotts** [comment]
we permit and have examples of level 5 headers in standards, so we should allow for ERs.

**Comment by serich** [comment]
I have no objection to the change itself. I'm confused about the procedure, though, and why @ghobona doesn't just make the change himself directly.

In fact, I've never figured out who is accountable / responsible for maintaining this repo, so I'm not sure who Gobe's request was directed toward. Greg and I have loaded the ER repos at the beginning of each testbed. But it seems that the template itself is part of the broader Innovation Program, and it's apparently open to members too (e.g., Jeff Yutzler has contributed), leading me to believe that it might even be used beyond the Innovation Program.

Anyway, given the current state of openness of the template, I'd have no objection to Gobe going ahead and making this particular change directly himself. If anybody else objects to him being allowed to make the change, please speak soon. Otherwise, please feel free to go for it @ghobona .

**Comment by ogcscotts** [comment]
I think that we should move the ER template to the official OGC templates repo and have it managed by Gobe, Greg, and I as all other templates are managed.

**Comment by serich** [comment]
@ogcscotts +1 to that idea.

**Comment by ghobona** [comment]
Fixed by https://github.com/opengeospatial/er_template/commit/efbe947fcfd17e412ff09be56933b6bf2f502cd4
